# Site settings for oby-wan.github.io

# Domain (used by some plugins to force HTTPS)
domain: oby-wan.github.io

# The base hostname & protocol for your site
url: "https://oby-wan.github.io"

# If the site is served at the root (as with user/organization GitHub Pages), leave baseurl blank
baseurl: "" # the subpath of your site, e.g. /blog

# Site settings
title: Tobhub
description: >-
  For the latest in IT tutorials and discussions

# Build settings
theme: minima

# Author settings (optional)
author:
  name: Toby the tech
  email: toby@tobhub.com

# Markdown processor
markdown: kramdown

# Permalinks
permalink: pretty

# Exclude these files and folders from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Plugins (optional, minima theme may require jekyll-feed)
plugins:
  - jekyll-feed

# Pagination (optional)
paginate: 5
paginate_path: "/page:num"
